### ISSUE TITLE
gem cd

### ISSUE THREAD

**Issue by akahn** [tpope/gem-browse#2]
I often want to simply change to the directory of an installed gem, and ack around, or vim something, but not go directly to vim (as in `gem open rails`).  Would you accept a patch for `gem cd rails` that simply changes to the directory of a gem?

**Comment by erikw** [comment]
@tpope `gem cd` could spawn a subshell in the gem directory right?

I think that would be fine! It should maybe be named `gem enter` instead to indicate that it's not a `cd` though.
