### ISSUE TITLE
Linux -- use xdg-open instead of open

### ISSUE THREAD

**Issue by davidosomething** [tpope/gem-browse#8]
on linux the open command used by `gem browse` is not how you open associations,
`xdg-open` or `gvfs-open` are common implementations

**Comment by davidosomething** [comment]
or use env $BROWSER if it is available

**Comment by tpope** [comment]
It's using `git web--browse`. If doesn't work your git config might be to blame.

**Comment by davidosomething** [comment]
thanks!
resolved by updating my .gitconfig with
```
[web]
browser = xdg-open
```
